[build]
target = "./index.html"
dist = "dist"
public_url = "./"      
hash = false  # 禁用哈希，保持文件名稳定                                                        

[assets]
[[assets.copy]]
src = "dist/tailwind.css"
dest = "dist/"  # 明确指定目标目录（可选，确保与引用一致）

[watch]
paths = [
  "./src/**/*.rs",
  "./index.html",
  "./styles.css",
  "./tailwind.config.js"
]
# 确保命令能在 Windows 上正确执行（使用 npx 避免路径问题）
before_build = ["npx tailwindcss -i styles.css -o dist/tailwind.css --minify"]
command = "npx tailwindcss -i styles.css -o dist/tailwind.css --minify"
ignore = ["Cargo.lock", "dist/"]  # 忽略生成目录，避免循环触发

# 监听的文件路径
# 启动监听前先执行一次CSS生成
# 当监听的文件变化时执行的命令
[serve]
port = 1420
open = false
# 设置正确的MIME类型
default_mime = "application/octet-stream"
[serve.mime_types]
"wasm" = "application/wasm"
"js" = "application/javascript"
